### ISSUE TITLE
Synchronization resets round extension data

### ISSUE THREAD

**Issue by coder13** [thewca/wca-live#100]
I just started developing a website to that utilizes the `extensions` array on the `round` object and noticed that the extensions get reset when I synch with wca-live.

Issue I think is in this function:

https://github.com/thewca/wca-live/blob/8f30b4ca621fe3a132a0ea8dca474880a4464c47/server/lib/wca_live/synchronization/export.ex#L117

**Comment by jonatanklosko** [comment]
Hey Caleb! When sending WCIF to the WCA website we don't include the `"extensions"` key at all, in which case the WCA website shouldn't change them ([ref](https://github.com/thewca/worldcubeassociation.org/blob/44691156efd03aa1ca2984f18ce85c96a2d63ac6/WcaOnRails/app/models/competition_event.rb#L55)). Groupifier uses a couple extensions and the sychronization works fine.

Please double-check if you can reproduce the issue with those steps:

1. Store the extensions using your tool
2. Go to the WCIF endpoint and ensure the extensions are there
3. Hit Synchronize in WCA Live
4. Refresh the WCIF endpoint and ensure the extensions are not there

**Comment by coder13** [comment]
I can confirm the extension is present after #2 and after synchronizing with wca-live, it's missing.

**Comment by jonatanklosko** [comment]
I found a bug in the WCA import, it would always recreated the round (delete + create), so if extensions were missing they would indeed disappear. See https://github.com/thewca/worldcubeassociation.org/pull/6966.

Sidenote: this wasn't a problem for Groupifier, because it doesn't use extensions on rounds.

**Comment by coder13** [comment]
Thanks for investigating!
