### ISSUE TITLE
Improve scalability

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/wca-live#105]
Large competitions can generate a huge traffic, especially in case of important rounds or records and this may overload a single server instance. Other than that, the traffic is inherently high over weekends and low otherwise. In this context, a clear optimisation would be to enable autoscaling to multiple server instances (or containers).

Currently the app includes a separate docker containers that handles SSL certs and serves static assets, those can be replaced with appropriate services. The app server is already a standalone container that just needs a couple secrets. However, an important detail is that the app server uses an in-app pubsub (for real-time result updates), so to work in multi-instance setup, we want to connect all instances into a single cluster using Erlang Distribution, so the pubsub continues to work.

There may be other in-app optimisations, but given the expected spikes in demand, employing a more scalable infrastructure is most likely what we want.

**Comment by campos20** [comment]
Depnding on how much we are willing to change the current infrastrucuture. We have more options on the table. In slack, we talked about fargate (which can scale on demand). We should probably use an external message queue (maybe SQS, SNS or kinesis, if we don't mind marrying AWS; Kafka, RabbitMQ... if we do mind) instead of the internal one. It's better than managing our put/sub server by ourselves. We can also use dynamo and use its natural stream to replicate data do our database and send changes somewhere else.

**Comment by jonatanklosko** [comment]
> We should probably use an external message queue (maybe SQS, SNS or kinesis, if we don't mind marrying AWS; Kafka, RabbitMQ... if we do mind) instead of the internal one. It's better than managing our put/sub server by ourselves.

The Erlang VM that Elixir runs on (think JVM for Java) is all about process messaging, to the point where it works transparently across multiple machines as long as they are connected into a cluster. This makes it easy to implement a distributed PubSub, and the web framework that we use comes with one already, so we are not maintaining any PubSub of our own. This is a preferable solution for in-app broadcasts, because it's simple to use and doesn't depend on an external service :)

**Comment by dahermansson** [comment]
Is separate the views for public results and the admin-part something to consider? During the weekend we experienced difficulty to submit scores to WCA-live. If the public site is on a other server/node it is not us vulnerable as it is now. It's a bit bad that an attack (no attack this weekend, just heavy load. But it shows it's possible and easy to arrange evil things to dameage competitions) on a public site can take down the admin-part that most (all?) competitions relight on during a competition.

**Comment by jonatanklosko** [comment]
A new infrastructure from #140 is now deployed. It features CPU-usage based autoscaling that spawns more instances, and all app nodes automatically form a single cluster.
