### ISSUE TITLE
Allow results to be sorted alphabetically by first name

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#12]
This would make scorecard checking much easier.

**Comment by jonatanklosko** [comment]
Just so you know: there's a dedicated double-check screen, which makes it straightforward as long as you put scorecards on a pile as you do dataentry. If you still believe sorting makes sense, we can obviously add a that!

**Comment by sarahstrong314** [comment]
That's awesome! 

Sorting would still be useful to prevent using CTRL+F hundreds of times.

**Comment by jonatanklosko** [comment]
Fixed in 060b73af7c81f5101dc90475a35ba78a3ed6a315.
