### ISSUE TITLE
Change "PB" to "PR"  in personal results section

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-live#121]
As this [forum thread](https://forum.worldcubeassociation.org/t/changing-wca-live-to-pr-instead-of-pb/28111) notes, the emerging convention is to use "PB" (personal best) for one's best time overall, and "PR" for best time achieved in competition.

While I don't think the current wording is "highly misleading", I do think PB/PR is a helpful convention that I'm assuming it would be trivial to implement.

**Comment by kr-matthews** [comment]
WCA profiles literally say "Current Personal Records" so PR is technically correct; the current usage of PB in WCA Live is inconsistent with the WCA site. PR is also consistent with WR, CR, and NR.

![image](https://user-images.githubusercontent.com/49137025/201976023-fcd94379-1ebd-4f80-9969-53cd50e6e044.png)

**Comment by jonatanklosko** [comment]
Closed in #122.
