### ISSUE TITLE
Make it clearer when advancing competitors have been finalized

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#128]
It's not obvious to a new competitor that the advancing competitors are not finalized until all results for the round are in. A few ideas:
* Display a disclaimer saying that advancements are not final until all results are in.
* Display the percentage of results of the round have been entered.
* Make the advancing ranks yellow instead of green until all results for the round have been entered.

**Comment by Tobus2** [comment]
I second this (as per the mention) - it can be misleading to new competitors (I've seen 8yo kids in tears as their parents try to explain!), and there's no clear indicator of when the results are "final".... when I'm close to the cutoff I usually scroll to the bottom and see if there are any names left with no times to see if I've really made it or not.

I think a clear visual cue like a different colour (border/format?) for either all unfinalised rankings or just ones that could still be pushed out of the cutoff, is a great idea and would still retain the experience of a coloured "space" where competitors "jump into" over the earlier competitors. It would just make it easier to see who has definitely made it and who might still be pushed out.

Text saying "Final" or "In Progress - subject to change" at the top would be great too.
