### ISSUE TITLE
Implement certificates

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#13]
This is a very useful feature of Cubecomps that I hope WCA Live also includes. 

If possible, it would also be nice if admins could test out certificates design with dummy data to see how it would look. In Cubecomps, this is not possible unless there are results posted. Cubecomps also has limitations on the style tags (e.g. you can't bold and centre text at the same time) that weren't great.

**Comment by jonatanklosko** [comment]
Actually, I strongly think it's out of the scope of WCA Live. This is a perfect use case for a dedicated app (which fits our vision). Also with an app built with that in mind you can definitely expect better designs/editing features. See the [concept](https://github.com/thewca/wca-live/blob/master/docs.md#concept) and note on [3rd party apps](https://github.com/thewca/wca-live/blob/master/docs.md#3rd-party-apps).
