### ISSUE TITLE
PR overlaps other content

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-live#135]
On smaller screens PR overlaps onto other text:
![4325DF0B-A644-4CF1-8B9A-94E2C5570D89](https://user-images.githubusercontent.com/11577241/212547558-a5fc72b6-5042-41db-9b8a-4e916348054d.jpeg)

**Comment by jonatanklosko** [comment]
Hey @Jambrose777! The projector view assumes a horizontal full-width screen, it is not optimised for smaller screens, it is specifically designed for displaying results on TVs or wall projectors at the competition; we even hide that option on mobile.
