### ISSUE TITLE
Inconsistency in multiblind results

### ISSUE THREAD

**Issue by pawelduraj** [thewca/wca-live#136]
It's possible to enter the result 14/14 1:00:30 for multiblind attempt. However it's not possible to enter the result 15/15 1:00:32. In the first case it's possible to add time penalty +2 seconds for something other than one move on each cube. In the second case it's not possible, but there is only 1 cube difference, so it should work the same.

**Comment by jonatanklosko** [comment]
Actually the current check allowed an arbitrary 30s just in case, but I changed it to 4s per attempted cube, which should be a better heuristic :)

Closed in 3961dd5e57daa0d37cac929e62bfa442e5a21623.
