### ISSUE TITLE
Groupless scorecard generation

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-live#14]
Are there plans to create some method of generating scorecards that don't have a group tied to them? I'm excited at the prospect of WCA Live but am hesitant about switching over due to using my own grouping methods.

**Comment by jonatanklosko** [comment]
First of all WCA Live is [designed](https://github.com/thewca/wca-live/blob/master/docs.md#concept) to be used for dealing with results only, so it's not opinionated on how you actually do groups and generate scorecards. At this point we suggest Groupifier, as it handles both grouping and scorecard generation and is compatible with WCA Live (it knows how to talk to the WCA website to load/save the necessary information). It's a external app, and so could be replaced by any other software as long as it satisfies the organizer needs. In general grouping and scorecard printing are two separate tasks and there's a wide variety of functionalities related to each of them, so in the future we will most likely have a dedicated app for scorecards printing and various grouping solutions developed by other people. You can read more on that [here](https://github.com/thewca/wca-live/blob/master/docs.md#3rd-party-apps).

At the moment one workaround would be setting just 1 group for every round in Groupifier, which would correspond to what cubecomps does now.

I hope that clarifies things. Closing the issue as there's nothing to do in this matter on WCA Live side.

(Btw. Groupifier provides several sorting rules to put people in groups, I'd be happy to chat about the details of what you usually try do accomplish to see if this could be done with Groupifier or what poses the problems).

**Comment by KitClement** [comment]
Got it, thanks for the suggestion! I'll give that a try sometime to get comfortable with how scorecard generation would work before and during a competition. (edit: just played around with a comp and did this, and the cards come in a random order rather than alphabetical, so this isn't really workable for manually sorting based on our own groupings.)

I'd be happy to chat about Groupifier if you'd like! Feel free to reach out when you have time, I'll be busy for the next week or so but would be happy to chat about it after that.

**Comment by jonatanklosko** [comment]
As for the random order, scorecards are sorted from worst to best, but yeah that makes the workaround less useful for you. First of all I'd like to see if your needs could be satisfied by appropriate Groupifier configuration (or some reasonable changes to the available options), ping me on Facebook after your busy time is over =)

**Comment by Goosly** [comment]
> just played around with a comp and did this, and the cards come in a random order rather than alphabetical, so this isn't really workable for manually sorting based on our own groupings

Manual sorting into groups is a nightmare even when the scorecards are sorted alphabetically
I highly recommend using a tool that generates scorecards already sorted by groups (and that mention the group on the scorecard - no confusion possible at the competition too)
