### ISSUE TITLE
Sync timing out

### ISSUE THREAD

**Issue by timreyn** [thewca/wca-live#141]
I tried importing CubingUSANationals2023 into WCA Live, and when I sync, it times out after 10-15 seconds. I'm not sure which request is causing the timeout, but I would guess it's the WCIF patch. Would it be possible to increase the timeouts?

**Comment by jonatanklosko** [comment]
I've increased the timeouts in 80f0dc4688b5f66dfc74bcc4ba30e35dddd599a6, let me know if it helps :)

**Comment by timreyn** [comment]
Thanks! It succeeded in 37 seconds.
