### ISSUE TITLE
U.S. Competition (Up in the North 2023) displaying with Canadian flag

### ISSUE THREAD

**Issue by AlyssaHope** [thewca/wca-live#144]
![image](https://user-images.githubusercontent.com/67570875/228119140-da9df63f-e1e0-470b-97af-a2683e7396c1.png)

**Comment by jonatanklosko** [comment]
Hey @AlyssaHope! The schedule venue is actually marked as Canada. I emailed the organisers, so this should be adjusted soon, thanks for noticing :)
