### ISSUE TITLE
Feature Request: Visually indicate newcomers

### ISSUE THREAD

**Issue by KerrieJarman** [thewca/wca-live#146]
There are numerous reasons where it would be useful to know that this is a competitor's first competition in the event view, not least for showing who is the highest ranking new comer. 

Currently the only way to do it is to do an export and then a manual lookup in excel or similar program.

The visual indicator could be very simple - a different coloured font or a small icon next to the name.  This would make it very easy to scan the list to identify all the newcomers in a particular event.

**Comment by jonatanklosko** [comment]
@KerrieJarman I think a visual indicator in the public results view would be too much clutter, but I would be fine adding it to the admin view (for scoretaking). Does that work for you?

**Comment by KerrieJarman** [comment]
Thanks @jonatanklosko that would be great
