### ISSUE TITLE
Incorrect PR

### ISSUE THREAD

**Issue by OtaMota** [thewca/wca-live#147]
It says that Luke Garret got a new PR this weekend (https://live.worldcubeassociation.org/competitions/2800/competitors/272926), but he had a faster result the week before (https://www.youtube.com/watch?v=FBo-MwYQBMI).

**Comment by jonatanklosko** [comment]
Hey, thanks for the report :) In this case it's expected, the results from last week's competition have been posted just yesterday, while this weekend's competition was synchronized only 2 days ago. False positives like this happen from time to time, but it's not that frequent, and also those records are just indicators on WCA Live, when they end up in WCA rankings it's always accurate.
