### ISSUE TITLE
certificates printing

### ISSUE THREAD

**Issue by bruchemrfe** [thewca/wca-live#15]
I could not find the printing of certificates.
This could be added to WCA Live or it would be good to export so that we can copy/paste.

**Comment by jonatanklosko** [comment]
Please, see #13.

**Comment by bruchemrfe** [comment]
Sorry, I did not know there were closed issues as well. :-)

And exporting the data?

**Comment by jonatanklosko** [comment]
WCA exposes so called [WCIF](https://github.com/thewca/wca-live/blob/master/docs.md#wording) with relevant information and WCA Live synchronizes results there, so they are all available. At this very moment getting WCIF via API requires authentication (only organizers/delegates can do that), but we plan to make it available publicly (omitting the secret data like emails and birthdates). Once this is done it should be even simpler to write [integrated software](https://github.com/thewca/wca-live/blob/master/docs.md#3rd-party-apps).
