### ISSUE TITLE
Cannot enter sub-minute Multi-Blind result

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#160]
It thinks results under 1 minute are "impossible". Elliott Kobelansky just got a sub-minute 2/2 success and it won't let me enter it.

<img width="539" alt="elliott 2 out of 2 multi" src="https://github.com/thewca/wca-live/assets/5139750/a49dea7f-22fb-45a2-a6b7-dc7e804d5647">

When I click on _submit_, I get this error message:

> Cannot query field "enterResultAttempts" on type "RootMutationType". Did you mean "enterResults"?. Unknown argument "input" on field "enterResultAttempts" of type "RootMutationType".

I tried the following and none of them worked:
* 0:55
* 0:55.00
* 55.00
* 55

I ended up entering a dummy value of 1:00.

**Comment by jonatanklosko** [comment]
Hey @sarahstrong314, the confirmation is expected, but it's just a warning, `55.00` is fine and Submit should work.

> Cannot query field "enterResultAttempts" on type "RootMutationType". Did you mean "enterResults"?. Unknown argument "input" on field "enterResultAttempts" of type "RootMutationType".

This is a caching issue, looks like the client-side WCA Live code did not update for you. Please try a hard refresh with ctrl/cmd+shift+r, or if for some reason it still doesn't work use an incognito window.

**Comment by sarahstrong314** [comment]
It worked, thanks!
