### ISSUE TITLE
Feature request: use session storage as temp storage for batch mode

### ISSUE THREAD

**Issue by Rubiks-boy** [thewca/wca-live#161]
Hi, thanks for adding batch mode!

Due to poor internet, we were trying to use it for a recent competition. However, our internet dropped entirely, and we ended up refreshing the page, which cleared our batch of scorecards.

would it be possible to use session storage as a temp location for storing batches until a batch is submitted?

**Comment by jonatanklosko** [comment]
In the initial implementation I want to added an alert to prevent from refresh/navigation, but it turned out that react-router that we use doesn't have a good API for that currently. Persisting to local storage sounds good! Added in #163.
