### ISSUE TITLE
Bug: Batch mode doesn’t preserve order for double checking

### ISSUE THREAD

**Issue by Rubiks-boy** [thewca/wca-live#162]
Hi, batch mode is a really cool addition! We were using it for a recent comp, but in our limited testing, it seemed like they might have gotten out of order when we went to double check them. Would it be possible to make sure batches preserve the order they were submitted?

**Comment by jonatanklosko** [comment]
Good call, we order results by entry time, but currently we set it on the server when results are submitted. Since in the batch case submission is deferred, all results in the batch would effectively get the same timestamp. Improved in #163.
