### ISSUE TITLE
WCA Live Suggestions

### ISSUE THREAD

**Issue by 2021WHIT02** [thewca/wca-live#183]
As a scoretaker, I have a few suggestions for how to improve WCA live in order to make data entry much easier. First, I believe that in addition to the recently added bulk quitting feature, one should be able to enter a competitor's id or name as if they were entering their times, and a button to quit them should come up along with the time slots. The other suggestion I have is being able to see completion ids in non-scoretaker mode to make writing scorecards easier, so you don't have to sign in.

**Comment by jonatanklosko** [comment]
> one should be able to enter a competitor's id or name as if they were entering their times, and a button to quit them should come up along with the time slots

I think what we can do is have an option to see the same menu as when clicking result in the table. I opened #185.

> The other suggestion I have is being able to see completion ids in non-scoretaker mode to make writing scorecards easier, so you don't have to sign in.

The ids are not really relevant for the general public, so I wouldn't do that. I'm fine with showing the id on the specific competitor page, but not sure if that helps much for your use case.

Thanks :)
