### ISSUE TITLE
"Done" is often not the case for obviously completed rounds

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/wca-live#19]
basically, in cases where they never input the last few people (probably because they didn't get any results) it doesn't mark on the sidebar that the round is "done". Could this be fixed with a prompt asking for the round to be marked as done/removing the people that didn't compete, or just setting something that marks it as done after no results have been inputted for lets say an hour or so (adding exceptions for stuff like FMC where every last attempt is DNS)

example: https://live.worldcubeassociation.org/competitions/WestcoastWoodvaleWeekends2019/rounds/555-r1 
![image](https://user-images.githubusercontent.com/48773372/65823937-a6b81b80-e22d-11e9-87bf-d64ea8824e62.png)

**Comment by jonatanklosko** [comment]
Fixed in 7cd658a408de36ef882e59a43ee1d8d1d837b67b.
