### ISSUE TITLE
Double Checking ordered first by Scoretaker, then by Timestamp.

### ISSUE THREAD

**Issue by OJCubing** [thewca/wca-live#196]
This would allow for two scoretakers to be able to do data entry for the same round simultaneously and keep the scorecards they've entered in their own piles. Currently when doing simultaneous data entry, you have to try to place submitted scorecards in a shared pile, which can be messy and scorecards often get slightly out of place due to delays in submitting.

This feature would be particularly useful for major championships. I would love to be able to use this at UK Championships on 20th October, however I appreciate it if it can't be implemented that quickly.

Originally discussed in #188, then rethought into a cleaner solution, so remaking as a more accurate issue.

**Comment by timreyn** [comment]
I think this is the same as #133

**Comment by OJCubing** [comment]
You're right, apologies. Tried scanning for it quickly but couldn't see anything.
