### ISSUE TITLE
Make roles editable for organizers/delegates

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-live#2]
More specifically, it would be awesome for organizers/delegates to be able to mark someone as a "staff-dataentry" similarly to what is possible in groupifier.

**Comment by jonatanklosko** [comment]
It's not something you'd do often, so for now I think it's ok to edit that in Groupifier's role editor and just synchronize, but if it proves not enough we can definitely add that =)

**Comment by AlexKatyukov** [comment]
Another task if the score-taker is not a competitor or organizer. In cubecomps organizers can just provide them a password, in WCA Live it's not so easy.

**Comment by viroulep** [comment]
@AlexKatyukov I think this one deserves a separate issue ;) #9 

>I think it's ok to edit that in Groupifier's role editor and just synchronize, but if it proves not enough we can definitely add that =)

The thing is that:
  - Groupifier is not a WCA tool (although a whole lot of competitions use it!)
  - roles defines who can access WCA Live, so it makes sense to be able to edit them from there
  - going back and forth between both tools is not great

But I agree that currently this is of course a very acceptable workaround.

**Comment by jonatanklosko** [comment]
Implemented under a new Settings page.
