### ISSUE TITLE
Means are computed for big blinds

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-live#20]
While this is definitely the behavior we want on the results page, this is actually not yet supported by the website (see thewca/worldcubeassociation.org#4577).
The plan is to merge the mentioned PR as soon as the workbook assistant is updated, altogether with the PR on scrambles matcher here: viroulep/scrambles-matcher#1.

Until then, is it reasonable to not sync big blinds average to the WCA website (ie: set them to 0 in the saved WCIF)?

**Comment by SAuroux** [comment]
> Until then, is it reasonable to not sync big blinds average to the WCA website (ie: set them to 0 in the saved WCIF)?

Absolutely! WCA live should always stick to what is supported by the website.

**Comment by jonatanklosko** [comment]
Actually as we store live results separately on the WCA website I think it makes sense for them (i.e. the WCIF) to include means. It's just the `results.json` that should include zeros, so I suggest either doing that in scrambles matcher or proceeding with the WA and website updates if possible.

**Comment by viroulep** [comment]
hum right, I've taken care of this in viroulep/scrambles-matcher@891805419c51b85c00a3b8244bc4949acfc8676d

I guess we can close this then!

**Comment by jonatanklosko** [comment]
Perfect, thanks!
