### ISSUE TITLE
Do calculations when attempt is registered on API / from external device

### ISSUE THREAD

**Issue by Citaborg** [thewca/wca-live#200]
The API for registration of attempts works, but I miss the timelimits calculations done in WCA.

Recreate: 
Define a round with time limit 2 mins, cutoff 1min (or cumulative time limit of 2 mins). 
Enter 5 attempts with 3 minute each through API.
WCA Live now lists 5 attempts with 3 minutes and an average of 3 minutes.

**Comment by jonatanklosko** [comment]
Closed in 39198ad80109d991a1154c0ed616210eb61f8c33.
