### ISSUE TITLE
Using the API to enter attempts is slow

### ISSUE THREAD

**Issue by Citaborg** [thewca/wca-live#201]
We had average of > 1.5 seconds for each POST during competition which I consider very slow.

**Comment by jonatanklosko** [comment]
I don't think there is any obvious inefficiency. Entering an attempt updates positions (and possibly record tags) for other results in the round, so when there are many competitions it puts certain load on the database and instances. We have automatic scaling to keep it manageable in general.

For an external device, waiting additional 2s to finalise the attempt at the station I would consider fine. From #202 I gather you use a scanner, so I can see how the delay is more noticeable. I think we can improve this by #202 with batch mode, I will comment there :)
