### ISSUE TITLE
Set a NULL MX for the subdomains

### ISSUE THREAD

**Issue by d4rklynk** [thewca/wca-live#203]
It seems you dot not use email for the subdomains live.worldcubeassociation.org

As per the [RFC 7505](https://www.rfc-editor.org/rfc/rfc7505#section-3), you should set a NULL MX.

It's a special instruction that says the domain will not accept receiving email.

In practice, it looks like so:
*I sent an email to one of **my** subdomains, I received 1 minute later this email.*

![image](https://github.com/thewca/wca-live/assets/74207682/b5ee95cb-f5d0-4f55-9391-ab43ae94550c)

As you can see, it know instantly that it can't send the email to that subdomain -> end of story.

See how it looks in DNS:

![image](https://github.com/thewca/wca-live/assets/74207682/9d30fdae-861e-4768-8643-3d3fae17c43d)

**Comment by d4rklynk** [comment]
This NULL MX should be set for every subdomains an domains that do not use email.

**Comment by jonatanklosko** [comment]
Thank you, I added the record :)
