### ISSUE TITLE
Set SPF to always fail

### ISSUE THREAD

**Issue by d4rklynk** [thewca/wca-live#204]
As per the [RFC 7208](https://www.rfc-editor.org/rfc/rfc7208#section-10.1.2) (Section 10.1.2)
You should set spf value to:

`live.worldcubeassociation.org.   IN TXT  "v=spf1 -all"`

Doing so will fail every email that will be sent from this subdomain since this subdomain is not used for email.

If [DMARC on the apex domain](https://github.com/thewca/worldcubeassociation.org/issues/7770) is configured to reject email for subdomains (`sp=reject`), the email will fail SPF check, so it will not be sent to users.

**Comment by d4rklynk** [comment]
Like [NULL MX](https://github.com/thewca/wca-live/issues/203), it should be set for every domains and subdomains that do not use email.

**Comment by jonatanklosko** [comment]
Done, thanks! We have DMARC with `p=quarantine` (and without `sp`) and my understanding is that this also applies to subdomains.

**Comment by d4rklynk** [comment]
Yes, if `sp`is not specified, `p` will take over. It's always best practice to specify it though, in case you use `quarantine` in your apex domain, you should explicitly reject email for subdomains -> `sp=reject`.

**Comment by jonatanklosko** [comment]
We do have a subdomain allowed to send emails, so in this case we probably want to handle it the same as apex.
