### ISSUE TITLE
Can't sort admin results table by rank after sorting by something else

### ISSUE THREAD

**Issue by nsilvestri** [thewca/wca-live#208]
Sorting the admin table visible while doing data entry by something other than the "#" column makes it impossible to re-sort without going back and forward in the pages again. This column should probably be marked as sortable. 

I would make a PR but i'm doing data entry rn and stopped just for this issue

**Comment by jonatanklosko** [comment]
Fixed in f11c7634e9778f8bd4098908a138f90800541669.
