### ISSUE TITLE
Input displays all competitions in the database

### ISSUE THREAD

**Issue by maxidragon** [thewca/wca-live#211]
When generating the scoretaking token, the input displays all competitions from the database, even those to which I don't have access

![image](https://github.com/thewca/wca-live/assets/94986692/85095c3b-0fe1-4481-a042-db7db7da9aa7)

**Comment by jonatanklosko** [comment]
Yeah, this is a generic competition search. If you try to generate a token for a competition you can't scoretake for, we show an error message. I think in this case it's fine because the user looks for a specific competition, and otherwise we do validate access.
