### ISSUE TITLE
Prevent 0/0 from being entered as a result in MBLD

### ISSUE THREAD

**Issue by SK927** [thewca/wca-live#213]
It seems possible to enter invalid results for MBLD attempts:

![Capture](https://github.com/thewca/wca-live/assets/96429132/a3eb4109-a8f4-4b9e-b004-8e3ff1283ccd)

Steps to reproduce: Only enter a time before submitting the attempt result. 

Expected behavior: A warning or store the result as a DNF.

**Comment by jonatanklosko** [comment]
Good catch, we expected the values to be entered left-to-right and have completion logic accordingly, but we don't really enforce it. Fixed in 998c697022b950c7a3991a74527002c1ab54313b.

**Comment by SK927** [comment]
I would have expected people to enter the results properly too :D
Thanks for correcting it.
