### ISSUE TITLE
Former WR is displayed in recent records section

### ISSUE THREAD

**Issue by maxidragon** [thewca/wca-live#217]
![image](https://github.com/thewca/wca-live/assets/94986692/1d3aea78-d7ea-42f7-a7b1-280110669c1a)

WR single is now 2.31, and it was broken after Carter's single. Also, just after Eryk's 2.31, everything was fine (a week ago). If I'm not mistaken, Carter's record showed up today

**Comment by jonatanklosko** [comment]
Both Carter's and Eryk's singles are actual WRs, it's just that Carter's competition start date is one day later, so records from that competition disappeared one day later (it actually disappeared already). Technically we could compare the listed records with all records in the WCA Live database, but doing this for all regional records is actually a non-negligible amount of computation. Given that this is a very specific edge case (and that record tags are generally non-strict indicators), I think it's acceptable :) Either way, thanks for documenting the case!
