### ISSUE TITLE
Incorrect PR single badges for entire rounds

### ISSUE THREAD

**Issue by AnnikaStein** [thewca/wca-live#218]
Dear WCA Live team,

we observe an issue at this competition: https://live.worldcubeassociation.org/competitions/5091

7x7 Rounds 1, 2 show PR singles for practically everyone, which is incorrect. Interestingly, after synchronizing, similar problems occur for 6x6 R1, R2. We don't see this issue for other events.

We imported the competition quite early, and we observed a (maybe) related problem: the first round of the day showed many persons who were at the present time not registered and which we had to quit all manually (i.e. not true no-shows, people who correctly unregistered historically).

Do you know what is the underlying problem here? Something you would suggest us to fix on our end?

Thank you.

Annika, on behalf of the RNPBJ team

**Comment by jonatanklosko** [comment]
Hey @AnnikaStein. Thank you for the report. This is very strange, there were a few weird cases with record tags before, as described in #145, but here it applied to everyone in the round. I resubmitted the first result, which forces the tags to be recomputed and it looks good now again. I'm going to close this and track in #145.

> the first round of the day showed many persons who were at the present time not registered

Opening a round creates empty results only for people who are registered and accepted. Perhaps you opened the round before synchronizing, so WCA Live didn't know that those registrations have been deleted.

**Comment by AnnikaStein** [comment]
Thank you for the quick reply and for fixing it for us.

And also thanks for the explanation with opening before synchronization, makes sense!

Kind regards,
Annika
