### ISSUE TITLE
Already announced competition had new events added, synchronize throws error

### ISSUE THREAD

**Issue by maconard** [thewca/wca-live#22]
For the other competitions I have admin on, the synchronize button works flawlessly. But with this competition it was imported into WCA Live, had some events added by WCAT after announcement, and now pressing synchronize throws: `Cannot read property 'rounds' of undefined`

I am of course assuming that events being added is what caused the issue, since it should be the only difference, but if someone in WST could try to replicate this that would be great.

Cheers!

**Comment by jonatanklosko** [comment]
Fixed in a44c4b167674dd6ac6bc8345a2eef30f8a3f9f9a.

**Comment by maconard** [comment]
Thanks for the quick fix, Jonatan! The affected competition is tomorrow, just tested the synchronization and it worked great :)
