### ISSUE TITLE
For dark mode, change the light green of "could make next round" to dark green.

### ISSUE THREAD

**Issue by OtaMota** [thewca/wca-live#226]
Hello, I have recently noticed a new feature of WCA live where if you have a chance of making the next round or podium, your number is light green instead of a full green, which is reserved for confirmed next rounds/podiums. For light mode, I think its good and makes sense as light green is in between the green of confirmed in and the white of confirmed out. For dark mode, I think there could be some improvement.
![Screenshot 2024-08-03 at 11 11 21](https://github.com/user-attachments/assets/811b0609-9e25-44f0-8849-8e722ef918a4)

For dark mode, as the "confirmed out" color is now black, perhaps make the "possible in or out" color somewhere between the green and black so that the color can make sense, and perhaps (from what others have told me) it might not look as bad

**Comment by jonatanklosko** [comment]
Good call, adjusted and deployed :)
