### ISSUE TITLE
[BUG] Broken link (in certain cases) to edit rounds in the WCA website

### ISSUE THREAD

**Issue by Nanush7** [thewca/wca-live#229]
**Description:** the link in "You can view and change the rounds over on **the WCA**" doesn't work properly for competitions with certain characters in their name.

Example: the link for a competition named "Fátima en Montevideo 2024" (whose ID is "FatimaenMontevideo2024") points to `https://www.worldcubeassociation.org/competitions/FtimaenMontevideo2024/events/edit` (notice the missing `a` in the ID).

**Comment by jonatanklosko** [comment]
If you go to that competition now, it works. The competition WCA ID is editable, so what must've happened is that the competition was imported, then the WCA ID changed (added the missing a), so the id WCA Live had was wrong, and subsequent synchronization fixed it.
