### ISSUE TITLE
Make it possible to enter DNFs on iPhones

### ISSUE THREAD

**Issue by Rubiks-boy** [thewca/wca-live#233]
When entering a time on an iPhone, there’s no slash key. This means it’s impossible to enter a DNF:

![IMG_2097](https://github.com/user-attachments/assets/12c2108b-7fb8-46cb-9490-f47d9dead037)

Possible fix: also map # or + to enter DNFs

**Comment by jonatanklosko** [comment]
Good call, I made `#` also enter DNF in ab868fa62ffc7d2e1d77631d1d5cc3c9680d1947.
