### ISSUE TITLE
Head to Head with live input has unintended consequences

### ISSUE THREAD

**Issue by OtaMota** [thewca/wca-live#235]
<img width="1490" alt="Screenshot 2024-09-22 at 11 42 36" src="https://github.com/user-attachments/assets/af583bd7-01d0-4224-957d-898b2f54ecc3">

Here, Oliwier and Adam could be dropped from podium bc Tymon and Olaf could beat them, but despite that, Adam and Oliver's numbers are with the light green of confirmed podium, instead of the dark green of could be beaten

**Comment by jonatanklosko** [comment]
Good call, currently we only look at the empty results as possible contenders. Fixed in 5be51c774ecda6fff686df9f7779afb5a292ff80.
