### ISSUE TITLE
Show top 100 results

### ISSUE THREAD

**Issue by 2016AVER01** [thewca/wca-live#238]
Allow for filtering of recent top 100 (or custom amount like top 20) results. For example, below the WR/CR/NR list would be a list of recent results that made the top 100 rankings with the same filtering capabilities of the WCA rankings page. Or perhaps just add more specific and filterable date data to the rankings page.

**Comment by jonatanklosko** [comment]
Thank you for the suggestion. The live system doesn't currently have the information necessary to compute this and at this point I would consider this out of scope. We can revisit in the future when the interfacing with the main website changes.

Also, in the future there could be more options in the official rankings, but there are other priorities related to the rankings that need to be addressed first.
