### ISSUE TITLE
Badge for new highest national ranking result

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-live#239]
When a competitor switches citizenship, old results don't count towards the new country for rankings. It would be nice to show some indicator of a best result for the new country if it is not PR.

**Comment by jonatanklosko** [comment]
This is expected, in WCA Live the record tags are a snapshot in time. For example, when a new world record is established, we don't go and remove all world record tags from previous competitions.

WCA Live is used for results specifically during the competition, whereas the WCA website is the source of truth for results once they are posted.
