### ISSUE TITLE
Add Meta Title to WCA Live Page

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-live#247]
Request received via email "Title of WCA Live page"
> Please add meta title to WCA Live page, so when you share a link in social media it will show what competition is inside the link.
https://live.worldcubeassociation.org/competitions/6795

![image](https://github.com/user-attachments/assets/c4fb2f9f-2483-4b31-a8b6-6a3369a5cc8a)

**Comment by jonatanklosko** [comment]
Changing the title is a good idea, it helps to distinguish between multiple opened tabs. Added in 5702cadbcc94610b463ed43d168b6a9c13288f00. Since we use client-side rendering, this may not necessarily help with social media previews, unless they actually "run" the page to generate the preview.
