### ISSUE TITLE
"Happening right now!" Is not always accurate

### ISSUE THREAD

**Issue by JMacdiarmid** [thewca/wca-live#25]
I live in New Zealand, so this was very noticeable with cubecomps - Our competitions would be listed under "upcoming" for several hours after they had already started, and be listed under "in progress" well after they had ended, often into the next day. Right now this is the case with WCA Live as well.
I wonder if it would be possible to use time zone/schedule information to make the "Happening right now!" list more accurate? I believe this information is already being used, as for Otago October 2019, I could see a progress bar under the current event, showing how far through the schedule we were.

**Comment by jonatanklosko** [comment]
Yeah, so what happens is that on the main page everything is displayed in UTC. I guess one reason is that it would be weird to show two competitions with the same date, one in progress and one upcoming. On the other hand, on the competition page we show localized schedule which is accurate to what actually happens. I agree that's not really the best, we should probably display competitions under "Happening right now!" based on the actual schedule, regardless of their UTC date.

**Comment by JMacdiarmid** [comment]
Right. Yeah, I mean it might be weird but that's just because time zones are weird. I think it's better to prioritise accuracy - especially because the purpose of the website is live results. People who want to check results for the competition will expect to see it listed under "happening right now!". Also, people who are interested in international competitions will expect that they'll be able to see live results for "happening right now!" competitions - when in fact, if they're far enough west, those competitions might not start for several more hours.

**Comment by jonatanklosko** [comment]
I've modified the behavior in 5f3ce97b090658b26f48ccee51c230b46e26633b to treat a competition as in progress one hour before the first schedule activity, until one hour after the last activity. In other words a competition is considered in progress based on schedule + and additional 1 hour window.
