### ISSUE TITLE
Cursor doesn't automatically move to attempt 1 textbox when you click on "edit" under a competitor's name

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#26]
When you click on a competitor's name on the results page for a round, a dropdown menu with "Edit" appears. When you click on it, the competitor's name gets filled out on the left side, but the cursor doesn't get moved to the attempt 1 textbox -- you have to click into it to start filling in the competitor's result.

**Comment by jonatanklosko** [comment]
Fixed in ffc904b6abac5531ce23efec232a5a2e525fc402.
