### ISSUE TITLE
Adding icon for “favorites” webpages screen

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-live#28]
Some browsers (such us Safari) shows a small icon in the home screen when you add favorites websites. It would be nice if WCA Live have one.

Example of GitHub and WCA one:
![ADF4A239-1570-4850-BD27-0837A47804CC](https://user-images.githubusercontent.com/47502355/66349131-791f5080-e958-11e9-8b53-2e67f4ef6a78.jpeg)

**Comment by jonatanklosko** [comment]
Fixed in 830345a88c72587612790d4c8efe4305ce7817e8.

**Comment by Ivan-Brigidano** [comment]
@jonatanklosko why don't you use this image? I does looks better

![apple-touch-icon](https://user-images.githubusercontent.com/47502355/66456080-eb815500-ea6c-11e9-8b6f-025305d44aed.png)

**Comment by jonatanklosko** [comment]
I just went with the version that WCA Live uses (which fits the design better). Looks fine for me on Android, please add a screenshot of how it looks for you =)

**Comment by Ivan-Brigidano** [comment]
It looks a bit weird if you added to the home screen (emulating as if was an application). Specially compared to other apps icons (which usually are with white background). The icon I shared is the one that is used on the WCA website :P

![IMG_0002](https://user-images.githubusercontent.com/47502355/66459801-fd1b2a80-ea75-11e9-8129-765fe9124c3f.jpeg)

**Comment by Ivan-Brigidano** [comment]
And here is the WCA one, much more apple-like icon
![IMG_0003](https://user-images.githubusercontent.com/47502355/66460046-6ef37400-ea76-11e9-86ca-c5a62426338a.jpeg)

**Comment by Ivan-Brigidano** [comment]
@jonatanklosko ?

**Comment by jonatanklosko** [comment]
I've just updated the icon to have white background and more space around, but I will wait with the deployment as the server is a bit busy with competitions this weekend.
