### ISSUE TITLE
Display WCA IDs next to competitors' names in competitor list

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-live#29]

**Comment by jonatanklosko** [comment]
What's a real world use case when this comes in handy? I think the table should be kept concise to fit smaller screens.

**Comment by sarahstrong314** [comment]
It would be useful because there isn't a quick way to get to competitors' WCA profiles, especially when no results have been entered yet. It would also serves as a quick way to see which competitors are new.

**Comment by moralsh** [comment]
perhaps a better solution for this is to add a column with a WCA icon linked to the competitors profile when available, or just show it for desktop screens.

**Comment by jonatanklosko** [comment]
I don't think adding more columns to the dataentry table makes sense, instead I've added an admin competitor list where you can easily see all the WCA IDs, so it should do the trick.
