### ISSUE TITLE
Schedules should be accurate to local time

### ISSUE THREAD

**Issue by JMacdiarmid** [thewca/wca-live#31]
If I access the page for Polish Championship 2019, it appears to be a 4-day competition, starting late on Friday evening and finishing extremely early on Monday morning. This is displayed under "Schedule", and gives an inaccurate view of the actual schedule of the competition.
While I assume this is a feature designed to make it easier for the viewer to know when exactly events are taking place (relative to them), I think the progress bar that shows up under ongoing events is sufficient for that. Perhaps this could be an optional feature that can enable, to convert the schedule to their timezone, but I think the default should simply be to show the schedule in the local timezone of the competition, with the progress bar under ongoing events.

**Comment by jonatanklosko** [comment]
This is definitely intended and I have a strong opinion that's how it should work. You can always check out the schedule in competition's timezone on the WCA website (two clicks from WCA Live), whereas 
a local schedule is the most reasonable and useful way of presenting the information to the user. Progress bar itself it's just a small part of the information, as you usually want to see at what time do some events start and doing timezone calculations manually is just ridiculous is a terrible user experience.

**Comment by JMacdiarmid** [comment]
Hmm. Perhaps this is a labelling issue then? I agree that the information is useful for the viewer, but I still find it quite odd to look under "Schedule" and see events happening after midnight, or see the comp happening across more days than it's scheduled for.

**Comment by jonatanklosko** [comment]
Pretty sure it's just the matter of people getting used to it, as we've never really localized schedules before. Also when you think about it, such events are indeed happening after midnight for you and that's all that really matters ^^

**Comment by JMacdiarmid** [comment]
Maybe yeah, we'll have to see how people feel about it after it's been live for a while I guess. Maybe it just feels unintuitive to me because I live in New Zealand, so I'm very used to thinking in terms of other time zones.

**Comment by AlexKatyukov** [comment]
Maybe good idea to have a switcher? User lime zone / venue time zone? For example, I'll have competition in another time zone next week and it's a little bit hard for me (I have a problems with my mobile operator, it change time not always correct).
