### ISSUE TITLE
Suggestion: schedule navigator

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-live#32]
Right now you have the events listed on the left and the schedule when you go to the competition's main page.
It would be cool if we could toggle between event list (in WCA order) or round list according to schedule. That way it would be easier to navigate, without having to go back to main page every time or opening a new tab each time you click an event.

**Comment by jonatanklosko** [comment]
While I see the point, I think adding such option is a bit of an overkill, I'd rather not clobber the UI with options that are not **that** useful, to make it more intuitive for external visitors. Also the functionality itself is implemented by the schedule view and I think that's where it should be. If many people strongly support it, we may consider that, but for now I don't really feel it's valuable enough.
