### ISSUE TITLE
Icons on the top left can be misleading

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-live#33]
There are 3 icons on the top left corner:
![image](https://user-images.githubusercontent.com/1881933/67148534-d4194780-f276-11e9-91f3-2abd4bfe7674.png)

Eventhough they are all together, one of them actually works differently, since it's not related to the competition itself, but takes you to WCA Live main page.
More than once I clicked the little house thinking I'd go back the competition's main page :P

**Comment by jonatanklosko** [comment]
Changed in the new version, should be less confusing now.
