### ISSUE TITLE
add an icon for competition homepage/schedule

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/wca-live#35]
you have to go all the way back to the homepage and then open up the competition page again in order to go to the competition homepage/schedule, this could be solved by simply adding an icon to click to link to the homepage/schedule (example link: https://live.worldcubeassociation.org/competitions/CopperCountryCubingFall2019)
![image](https://user-images.githubusercontent.com/48773372/67641836-ebda7680-f8db-11e9-8907-3e0b6715ad06.png)

**Comment by jonatanklosko** [comment]
Do you mean competition WCA homepage, or just the WCA Live one?

**Comment by alexmaasswca** [comment]
> Do you mean competition WCA homepage, or just the WCA Live one?

just the wca live one, I linked to an example of one

**Comment by jonatanklosko** [comment]
In this case you can navigate to the home page by clicking on the competition name in the top bar. I think it's the best approach as it's one click away on the mobile as way =)
