### ISSUE TITLE
Use system light/dark mode

### ISSUE THREAD

**Issue by Nogesma** [thewca/wca-live#37]
It would be nice to have and option to let the website automatically switch between light and dark mode depending on if the user's device is using dark or light mode. 

Adding a pure black dark mode would also be nice for users with OLED displays.

**Comment by jonatanklosko** [comment]
I implemented this in 89c5eb743a5929556001a720533cc9fd2a6790d6, but it relies on [this](https://caniuse.com/#search=prefers-color-scheme) browser fracture and is not available in some older browsers. If there's anything more we could do, feel free to reopen.

**Comment by Nogesma** [comment]
It doesn’t seem to be working on my devices. I have tried in on Safari and Chrome  on iOS 13 and macOS 10.15

Edit: I can't reopen the issue as I am not a contributor.

**Comment by jonatanklosko** [comment]
The feature came out 22th September, perhaps you visited the app before and the theme type persisted in the local storage. Could you please clear page data (specifically local storage) and see if it works this time?

**Comment by Nogesma** [comment]
I didn't visit the website before the 22nd of September. Clearing page data doesn't change anything.

**Comment by jonatanklosko** [comment]
Hmm, in this case it seems like there's some place for investigation.

**Comment by jonatanklosko** [comment]
I've just checked it and it works as expected, so I'm closing this.
