### ISSUE TITLE
Use key code instead symbol for DNF and DNS

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-live#39]
Now:
If I want to give the competitor DNF or DNS i should enter 'd' / '/' or 's' / '*'.

But:
If I use caps lock or want to enter the result from mobile devise With Auto Shift and enter 'D', WCA Live ignored me. Also I want not to switch over keyboards if I use cyrillic keyboard and enter 'в' that is at the same key that 'd' for DNF and 'ы' that is at the same key that 's' for DNS.

Please:
Use key codes instead symboles for this task if it is possible.

**Comment by cdraugr** [comment]
Do you really wanna use `в` and `ы` for entering results?
It sounds terrible...

**Comment by AlexKatyukov** [comment]
I just want not to think about Caps Lock and keyboard layout.

**Comment by jonatanklosko** [comment]
I've changed it to ignore letter case (7da6a1d6f8375d231b5550fda39c331fbf3de6d2), but I'm not convinced it's intuitive to consider different keyboard layouts.
