### ISSUE TITLE
Event times are not accurate to local time

### ISSUE THREAD

**Issue by coder13** [thewca/wca-live#40]
Example here: https://live.worldcubeassociation.org/competitions/SnoCoFall2019

I ran this competition on Saturday. During which, we found that the reported times on it, despite saying they should be accurate to our local timezone (America/Vancouver), they were 2 hours ahead. Our event starting at 8:30 on the WCA website was reported to be starting at 10:30 on WCA-Live.

**Comment by jonatanklosko** [comment]
This is not the fault of WCA Live actually, [apparently](https://www.worldcubeassociation.org/competitions/SnoCoFall2019#competition-schedule) the competition/schedule timezone is set to America/Adak on the WCA website, which is 2 hours behind the actual timezone of the competition. So 8:30 according to America/Adak is actually 10:30 when you're in America/Vancouver.
