### ISSUE TITLE
Results with all DNS

### ISSUE THREAD

**Issue by Baiqiang** [thewca/wca-live#49]
Right now it allows results with all DNS and has weird ranks for them. You can have a look here: https://live.worldcubeassociation.org/competitions/FMCAsia2019/rounds/333fm-r1
![image](https://user-images.githubusercontent.com/2390434/71566398-41a4e800-2af2-11ea-90e5-fbab02cb7abf.png)

This is because when sorting results, both DNS and DNF are considered as infinity. https://github.com/thewca/wca-live/blob/master/server/logic/results.js#L27

I think it will be better to prevent such kind of results.

**Comment by jonatanklosko** [comment]
Given that all-DNS results are not valid anyway I agree we should just prevent from that by showing an error once someone enters such a result.

**Comment by jonatanklosko** [comment]
Fixed in c893c53c7c303070f6345d946111c203b10ee3b9.
