### ISSUE TITLE
Result-based advancement calculation should use e.g. average, not best single

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-live#54]
At BASC 24, the advancement first → second round of 3x3x3 is 22 seconds. This is based on the average:

> [9p2+](https://www.worldcubeassociation.org/regulations/guidelines.html#9p2+)) CLARIFICATION Result refers to the single or average that determines the ranking of the corresponding round.

But apparently WCA Live goes by best single result:

<img width="1726" alt="Screen Shot 2020-02-15 at 15 28 34" src="https://user-images.githubusercontent.com/248078/74596715-fdb96400-5007-11ea-9255-27d0c8acdbf7.png">

**Comment by jonatanklosko** [comment]
Oh wow, I actually misinterpreted this part. Fixed in 28bbc12abb16d18af6028887b28370eb464d46a6! Will also update the WCIF spec to state it clearly.

**Comment by Goosly** [comment]
The page of the competition on the WCA website does say it is based on the single result:
https://www.worldcubeassociation.org/competitions/BayAreaSpeedcubin242020#competition-events

**Comment by jonatanklosko** [comment]
That must've been misinterpreted the same way, see [all the advancement conditions](https://github.com/thewca/worldcubeassociation.org/blob/20cc8f080e0f605fbbaf405563b9d0a7c01ef635/WcaOnRails/config/locales/en.yml#L149-L162). I've just created https://github.com/thewca/worldcubeassociation.org/issues/5176 describing that.
