### ISSUE TITLE
Viewing the public podium page on WCA live breaks if you have 0 rounds scheduled for an event

### ISSUE THREAD

**Issue by maconard** [thewca/wca-live#56]
We had to cancel 4x4 due to organizer error and available venue time. Originally I just removed it from the schedule, but that caused errors in groupifier. I tried dropping it down to 0 rounds scheduled in the event manager, but then the public podium page on WCA Live breaks, instead of ignoring the 0 round event.

To reproduce: have an event in a comp and leave that event at "# of rounds?" (i.e. 0 rounds) on the WCA competition edit page, and synchronize to WCA Live. Obviously this isn't a super common case because the WCAT is needed to officially add/remove events, so we can only pseudo-remove it by setting it back to no rounds. However, if a comp has an event unset like this, WCA Live should probably ignore it instead of breaking.

**Comment by jonatanklosko** [comment]
Fixed in c2ec1a185685ffc725904faf8324e2caf658527b.
