### ISSUE TITLE
[Feature Request] Total count of competitors

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-live#57]
When entering results and double-checking, it would be useful to display the total count of scorecards (/competitors) that have been entered and even scorecards left to be entered. This number is not always the last place number due to ties (like 20 people triple DNFing in 3BLD). 

Maybe: 55/60 (if there are 55 competitors with results and 5 people still to be entered or quit.

**Comment by jonatanklosko** [comment]
What do you think of this?

![image](https://user-images.githubusercontent.com/17034772/75728107-253a4d00-5ce7-11ea-8cc2-a8ecda13b744.png)

**Comment by jonatanklosko** [comment]
Implemented in dfff5f42030e128c8fbceb87abf0f81dee558b9e.
