### ISSUE TITLE
Number of participated competitors

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-live#59]
We need some record with number of presented competitors (who have at least one event). It can be useful for media announcements and WCA Dues counting).
Maybe here https://live.worldcubeassociation.org/admin/competitions/<COMPETITION_ID>/competitors

**Comment by saranshgrover** [comment]
Doesn't https://live.worldcubeassociation.org/admin/competitions/<Competition_ID>/competitors already exist?

**Comment by AlexKatyukov** [comment]
I think you didn't catch my wish. For example, Tyumen Cube Fest 2020: there are 60 registered competitors and only 56 presented. I see 60, but I didn't see 56.

**Comment by Nanush7** [comment]
I agree with you Alex, it would be really useful for WCA Dues counting at the competition.
