### ISSUE TITLE
Schedule: Make times and timezones crystal-clear

### ISSUE THREAD

**Issue by Goosly** [thewca/wca-live#6]
Current behaviour: the schedule is shown in the timezone of the device

This might be great if the user is interested in watching the livestream, for example. But it's terribly confusing for competitors that travel to a competition in a different timezone (for example, from Germany to the UK), especially when it's not obvious ( for example a six hour difference will be obvious, a one hour difference won't)

Expected behaviour: make it crystal-clear that the times are shown in the current timezone (so, display which timezone it is). Or, display times in both the competitions' timezone and the current timezone.

**Comment by jonatanklosko** [comment]
Showing localized schedule is intended here, as the aim of WCA Live is to make it simple for people to track results, it's clearly the best approach to do the timezone calculation for them. Cases where it could be confusing as you described are extremely rare and in those you can always follow the link to the WCA website to see full schedule there. I agree that some kind of clarification about that is indeed something we want, for now I took the following approach:

![image](https://user-images.githubusercontent.com/17034772/65387874-72cf8880-dd4b-11e9-866e-87b577e1ad63.png)

I think this should do and it's mostly the matter of people getting used to more convenient schedules =) If it proves confusing (which I doubt), we can always improve the UI.

**Comment by Goosly** [comment]
Perfect, thanks!
