### ISSUE TITLE
WCA Live breaking on IOS

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-live#72]
When you go to a round on WCA Live on IOS (Iphone/Ipad, I haven't issues on Mac) which has not been completed, the site crashes.

Example taken from Windows 10: https://imgur.com/a/wcb9dP2
When a round is left like this, it is not possible to view the results on IOS and the entire page is just shown in white. Going back to the previous page also doesn't work, and you have to close the browser and open up WCA Live again to view other rounds/competitions.

**Comment by jonatanklosko** [comment]
Should be resolved by f7beabfded17b0a80ba32dc409835b75ceb4f266. I would appreciate if you could verify that it doesn't break for you the next time you navigate to a round like that =)

**Comment by DanielEgdal** [comment]
Unfortunately, that doesn't seem to have fixed the issue. [Of current examples](https://live.worldcubeassociation.org/competitions/490/rounds/7737), going to a Bo2 Multi-Blind round with only the first attempt completed the website will go completely white/crash on IOS still.

**Comment by jonatanklosko** [comment]
Could you check if that's also the case in an incognito window?

**Comment by DanielEgdal** [comment]
I cleared the cookies on my Ipad from the WCA. It works now for the above example. :). I'll return and close the thread once a new round is opened and see if it also works for those.

**Comment by jonatanklosko** [comment]
> I cleared the cookies on my Ipad from the WCA.

Alright, this seems to make sense as the fix I deployed only changes response headers, but some assets are still cached together with old response headers. I've just pushed a small client change that should invalidate the cache and gradually pick up the fix, so it should be fixed for everyone affected soon as well.

**Comment by DanielEgdal** [comment]
Great, thanks for fixing this quickly! I'll close the thread as the issue is resolved.
