### ISSUE TITLE
Duplicate records on homepage

### ISSUE THREAD

**Issue by timreyn** [thewca/wca-live#86]
reported on facebook https://www.facebook.com/groups/cyoubxfriends/posts/5433720153321060/

At Korean Championship Mini 2021, two people tied for a sq1 AsR average: https://live.worldcubeassociation.org/competitions/742/rounds/11365

On the WCA Live homepage, both records are listed as being set by Jaemin Chang:
![269290267_1550497415326364_2969991857210399294_n](https://user-images.githubusercontent.com/3885929/146644220-bd43bfc1-db53-4f8f-a059-3c029c4ef5f9.jpg)

**Comment by jonatanklosko** [comment]
Just deployed the patch, thanks for the report!
