### ISSUE TITLE
Password access for score takers

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-live#9]
In cubecomps it was very convenient to be able to access data entry through a competition-specific password.
There may be multiple reasons motivating this feature, the main one being that there are usually several score takers, and changing WCA account every group or round sounds pretty bad: I definitely do not expect anyone to agree to log in their account on someone else's computer.
And I seriously hope that any Delegate or Organizer would *not* let their account "open" for WCA Live while someone else is score taking.

Therefore I think implementing a password-based access would be worth!

**Comment by sarahstrong314** [comment]
This would also be useful for when the scoretaker doesn't have a WCA account. The scoretaker at my competitions isn't a cuber.

**Comment by jfly** [comment]
@sarahstrong314, that scoretaker should still be able to create a WCA website account, right?

**Comment by sarahstrong314** [comment]
> @sarahstrong314, that scoretaker should still be able to create a WCA website account, right?

They could, but they wouldn't necessarily be registered for the competition.

**Comment by jfly** [comment]
Ah, got it. And the only way to add someone as a scoretaker is through groupifier right now, and I guess that groupifier only lets you add people who are actually registered for the competition? If so, that's a real problem that we should fix in groupifier/wcif, because it's not super rare for staff members to not be competing at a competition.

To be clear, I think the problem that @sarahstrong314 raised is different from the very real problem that @viroulep originally raised, and we should also talk about how best to fix that. I'm not a fan of passwords, so I'd love a solution that does not involve passwords. If people log into WCA Live and then log *out* of the WCA website, does that get us closer to the desired behavior, @viroulep?

**Comment by jonatanklosko** [comment]
@jfly I'm building an access settings page on WCA Live, that will allow for editing scoretakers, but the limitation comes from WCIF, as `Competition#persons` includes only registrations + organizers/delegates. The case @viroulep had in mind is some laptop having a keylogger, and signing in on that laptop exposes your whole account (so it's understandable that someone doesn't want to sign in).

**Comment by jfly** [comment]
> access settings page on WCA Live, that will allow for editing scoretakers, but the limitation comes from WCIF, as Competition#persons includes only registrations + organizers/delegates

Maybe this is a reason why WCA Live is *not* the right place for editing roles, and it should instead happen on the WCA website?

Or maybe it does make sense for WCA Live to have a role editor, but maybe it should be possible to pick people who are not registered for the competition somehow (maybe by talking to a WCA "search users" api endpoint?

> The case @viroulep had in mind is some laptop having a keylogger, and signing in on that laptop exposes your whole account (so it's understandable that someone doesn't want to sign in).

Yeah, I think we're all on the same page here =) I was thinking that if you sign into WCA Live and then sign out of the WCA website, you might get the behavior that Philippe wants, without us having to build anything new.

**Comment by jonatanklosko** [comment]
> Or maybe it does make sense for WCA Live to have a role editor, but maybe it should be possible to pick people who are not registered for the competition somehow (maybe by talking to a WCA "search users" api endpoint?

We store `Person#roles` in the WCA database in a registration corresponding to the given user, so we'd need to build an ability to have non-competitor registrations or something like that.

**Comment by jonatanklosko** [comment]
Implemented under a new Settings page. We can always get rid of that if we ever figure out an alternative approach achieving all the things pointed out above.

**Comment by viroulep** [comment]
It looks awesome thanks!
