### ISSUE TITLE
Idea: Make clearing no-shows simpler

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/wca-live#96]
When I am doing data entry once I get to the end of a round I go through all the blank scorecards and remove that person from the round - this is a key check to make sure there isn't a missing scorecard or someone's results were entered using the wrong ID during data entry. 

Probably at small comps where there are 5 or so no-shows it is relatively simple, but at big 200+ competitor events there are typically a lot more and there are a lot of steps (click their name, click "Clear", confirm you want to do that) and the additional challenge of a ~10 second lag per person if you have slow-ish internet and a lot of people in the round that need to be removed. Obviously bulk removing them (just opening the following round) is dangerous in case there are missing scorecards etc, and in Australia at least we generally don't open the following round until the earlier round is all double checked. 

Idea, at some point within the data page as you finish data entry for a round, click a button somewhere to enter "clearing mode". This would take you to a list of all the names without results, and you could checkbox through the list to work out which ones to remove, and then click a "clear" button (probably with a confirmation after that) which then removes all those people from the round in one go.

**Comment by timreyn** [comment]
+1 to this -- after doing data entry at a few big competitions this summer, clearing felt like one of the slowest parts.

Another idea is to add another key (e.g. "q") that quits the current person -- so you type in their ID, hit "q", hit enter, there's a confirmation dialog, and you confirm that you want to clear them. That would be faster than scrolling to the bottom of a long list of competitors.

**Comment by jonatanklosko** [comment]
> Another idea is to add another key (e.g. "q") that quits the current person -- so you type in their ID, hit "q", hit enter, there's a confirmation dialog, and you confirm that you want to clear them.

I like the idea of doing that from the result form level, because this seems to be an efficient option when quitting based on empty scorecards. I'm not sure about "q", because we wouldn't be able to use that in the competitor search field, which could be fine, but is a bit inconsistent.

Alternatively we could have an icon to open the competitor menu for the selected competitor. This helps with scrolling, but still requires a couple clicks.

**Comment by robertvandeneynde** [comment]
> Another idea is to add another key (e.g. "q") that quits the current person -- so you type in their ID, hit "q", hit enter, there's a confirmation dialog, and you confirm that you want to clear them. That would be faster than scrolling to the bottom of a long list of competitors.

The issue #99 suggested to use the "delete" key to do that.

**Comment by KerrieJarman** [comment]
@jonatanklosko any further thoughts or updates on this issue?  we are doing more and more large competitions, sometimes with dozens and dozens of no-shows. Quitting people one-by-one is an unnecessarily labour-intensive process.  A "clearing mode" where you could just select no-shows and clear them in a bulk lot would be fantastic.

**Comment by jonatanklosko** [comment]
@KerrieJarman added and deployed :)
